### ISSUE TITLE
Cypress task autocompletion don't work.

### ISSUE THREAD

**Issue by HubertArciszewski95** [Shelex/vscode-cy-helper#24]
Hello,

The feature described here - [task autocompletion](https://github.com/Shelex/vscode-cy-helper/blob/12239d4a4c9eeb2f11217c4d05b3dcec8233068b/docs/tasks.md) is not working.
When I type cy.task("") then it don't show any suggestions.

I have my tasks defined in cypress.config.ts file.

**Expected behavior**
When I type cy.task("") I should get the autocompletion of defined tasks.

**Environment:**

-   Extension version: 3.5.1
-   VS Code version: 1.84.2
-   OS: Windows
-   Cypress: 12.9.0

**Comment by Shelex** [comment]
Hi @HubertArciszewski95 
Thanks for reporting an issue!

Yes, this happened due to cypress changed the way how tasks are registered, previously it was `plugins/index.js` file, now it is `cypress.config.js`/`cypress.config.ts` which may be anywhere in the project. So in v3.6.0 I have changed the lookup logic for registered tasks from just one file to any file that may contain task registration.

**Comment by HubertArciszewski95** [comment]
Hi @Shelex
Thanks for fast response and for the fix :)

BTW. I love this plugin, great work :)
