### ISSUE TITLE
Narrow down alias autocompletion to selected file

### ISSUE THREAD

**Issue by HubertArciszewski95** [Shelex/vscode-cy-helper#25]
Hello,
In your documentation [HERE](https://github.com/Shelex/vscode-cy-helper/blob/HEAD/docs/alias.md#alias-autocompletion) you wrote "Aliases will be selected from files in current folder."

In my opinion autocompleting aliases in scope of the files in current folder don't bring any value (I don't see it)
Because aliases are reset before each test run. So I don't see a reason to display autocompletion from other files in folder.

What is my problem with it?
So I find it disturbing.  Because I get a lot of duplicated alias autocompletions.
In files in current folder I use several times the same name of the alias.

![Capture139](https://github.com/Shelex/vscode-cy-helper/assets/33283544/ec904617-5efa-4f83-8e89-63af1eb79bff)

As you can see it gets very messy.

**Describe the solution you'd like**
I will be very happy if aliases autocompletion will be done only for current file.
Or providing option to change this behavior. From scope of files in current folder to only current file.

**Comment by Shelex** [comment]
Hi @HubertArciszewski95 
Thank you for your feedback.

> In my opinion autocompleting aliases in scope of the files in current folder don't bring any value (I don't see it)
Because aliases are reset before each test run. So I don't see a reason to display autocompletion from other files in folder.

Actually we were using aliases in page/functionality abstractions thus restricting alias lookup just for specific folder where those functions lived. For the sake of readability we also were assigning meaningful names to aliases, so almost never had duplicates in a list. As your use case may be different, I have released v3.6.0 with a new configuration option `aliasAutocompletionForCurrentFile` which could be set as `true` and in such case will search for aliases in current file only.

Hope that helps.

**Comment by HubertArciszewski95** [comment]
Hi @Shelex 
Thanks for fast response and for the fix :)
