### ISSUE TITLE
Add "skip" tag

### ISSUE THREAD

**Issue by y-spilnyk** [Shelex/vscode-cy-helper#3]
I want to ask about adding ".**skip**" tag after Set ".**only**".

This might be very helpful for users. Thanks

**Comment by Shelex** [comment]
Hi @Almazov-18 
Thank you for opening this feature request.

Published within version 2.4.0, if you have auto-update enabled it will be fetched soon.
Please note that this feature is configurable, in order to enable code lense for skip tag you can set it inside `cypressHelper.menuItems` object, `ItSkip` property to `true`, refer to [configuration](https://github.com/Shelex/vscode-cy-helper#configuration) section in readme for more details.
